---
title: "Tutorial number 8"
author: "Logan Mantz"
date: "10/24/2019"
output: html_document
---



## set up 
```{r setup, message=F, warning=F}
#install.packages("tidyverse")
#install.packages("lubridate")
library(tidyverse)
library(lubridate)
lm <- read_csv("https://datajournalism.tech/wp-content/uploads/2019/10/wichita.csv")


population_2016 <-tibble(subject_race = c("asian/pacific islander", "black", "hispanic", "other/unknown","white"),
num_people = c(19727, 42679, 63659, 12973, 246343))
```

```{r discover-the-dataset}
View(lm)
str(lm)
glimpse(lm)
colnames(lm)
lm <- lm %>% mutate(subject_sex=as.factor(subject_sex))
lm <- lm %>% mutate(subject_race=as.factor(subject_race))

```
```{r run-basic-descriptive-statistics}
summary(lm)
```

```{r}

race <- lm %>% group_by(subject_race) %>%
summarize(value =n(), prop=value/nrow(.))%>%
arrange(-value)
view(race)
```

```{r}

stops<- lm %>%
  count(subject_race)%>%
  left_join(population_2016, by = "subject_race") %>%
      mutate(stop_rate = n / num_people)

    
```



```{r}
bar <- ggplot(stops, aes(x=reorder(subject_race,stop_rate), y=stop_rate))+ 
  geom_bar(stat="identity", fill="red")+
  geom_hline(yintercept = 0) +
  labs(title= "Stopped Drivers by Race",
       subtitle = "African American drivers got stopped more than White drivers in the city of Wichita, Kansas")+
  coord_flip()
bar
```

